name: "JARVIS Setter"
description: "Szerver oldali élő MP3 audio streamer"
version: "1.2.0"
slug: "jarvis_setter"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
audio: true
full_access: true
privileged: true
devices:
  - /dev/snd:/dev/snd
map:
  - config:rw
ingress: true
ingress_port: 8097
panel_title: "JARVIS Setter"
panel_icon: "mdi:radio-tower"
